"""empty message

Revision ID: 67672e7c2987
Revises: 53dd4e6b10be
Create Date: 2024-02-27 23:31:54.343016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67672e7c2987'
down_revision = '53dd4e6b10be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('image_uri',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('image_uri',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
